[package]
name = "metropolis_1d"
version = "0.1.0"
edition = "2018"

[dependencies]
glutin = "0.28.0"
egui = "0.18.1"
egui_glow = { version = "0.18.1", features = ["winit"] }
rand = "0.8.4"
rand_pcg = "0.3.1"
